Pushing 3 Piplines

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -1,27 +1,40 @@
 name: Build and Push to ECR
 
 on:
-  push:
-    branches:
-      - main
+  workflow_dispatch:
+   inputs:
+    confirm:
+     description: "Type BUILD-AND-PUSH to confirm"
+     required: true
 
-      permissions:
+permissions:
   id-token: write
   contents: read
+
+env:
+  AWS_REGION: eu-west-2
+  ECR_REPOSITORY: threat-composer-app
 
 jobs:
   build-and-push:
     runs-on: ubuntu-latest
 
     steps:
+      - name: Validate confirmation
+        run: |
+          if [ "${{ github.event.inputs.confirm }}" != "BUILD-AND-PUSH" ]; then
+            echo "Confirmation failed. Exiting."
+            exit 1
+          fi
+
       - name: Checkout code
         uses: actions/checkout@v4
     
       - name: Configure AWS credentials (OIDC)
         uses: aws-actions/configure-aws-credentials@v4
         with:
-          role-to-assume: arn:aws:iam::ACCOUNT_ID:role/github-actions-ecr-role
-          aws-region: eu-west-2
+          role-to-assume: ${{ secrets.ECR_ROLE_ARN }}
+          aws-region: ${{ env.AWS_REGION }}
 
       - name: Login to Amazon ECR
         id: login-ecr
@@ -29,9 +42,8 @@ jobs:
  
       - name: Build Docker image
         run: |
-          docker build -t ${{ steps.login-ecr.outputs.registry }}/threat-composer-app:${{ github.sha }} .
+          docker build -t ${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPOSITORY }}:${{ github.sha }} .
 
-      
       - name: Push Docker image to ECR
         run: |
-         docker push ${{ steps.login-ecr.outputs.registry }}/threat-composer-app:${{ github.sha }}
+         docker push ${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPOSITORY }}:${{ github.sha }}
diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -1,27 +1,66 @@
-name: deploying terraform code to AWS 
+name: Deploying terraform code to AWS 
 
 on:
-  push:
-   branches:
-     - main
   workflow_dispatch:
-
+   inputs:
+    confirm:
+     description: "Type DEPLOY to confirm"
+     required: true
 
 permissions:
   id-token: write
   contents: read
 
 jobs:
-  build-and-push:
+  deploy:
     runs-on: ubuntu-latest
+    defaults:
+      run:
+        working-directory: ./infra
 
-    
-    
     steps:
+
+      - name: Validate confirmation
+        run: |
+          if [ "${{ github.event.inputs.confirm }}" != "DEPLOY" ]; then
+            echo "Confirmation failed. Exiting."
+            exit 1
+          fi
+
       - name: Checkout code
         uses: actions/checkout@v4
 
       - name: Configure AWS credentials (OIDC) 
         uses: aws-actions/configure-aws-credentials@v4
         with: 
-          
+         role-to-assume: ${{ secrets.TERRAFORM_ARN }}
+         aws-region: eu-west-2
+
+      - name: Install Terraform
+        uses: hashicorp/setup-terraform@v1
+        with:
+          terraform_version: 1.7.0
+
+      - name: terraform init
+        run: terraform init
+
+
+      - name: terraform fmt
+        run:  terraform fmt -check
+
+      - name: setup tflint
+        uses: terraform-linters/setup-tflint@v1
+        
+      - name: tflint
+        run: tflint --config .tflint.hcl
+         
+      - name: Run terraform validate
+        run:  terraform validate 
+
+      - name: terraform plan
+        run: terraform plan 
+        
+      - name: terraform apply with SHA as variable 
+        run: terraform apply --auto-approve -var="image_tag=${{ github.sha }}"
+         
+
